name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  
  fluttertoast: ^8.2.1
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.10
  image_picker: ^0.8.7+4
  persistent_bottom_nav_bar: ^5.0.2
  carousel_slider: ^5.0.0
  auto_size_text: ^3.0.0
  geolocator: ^9.0.2
  http: ^1.2.2
  pdf: ^3.6.0
  path_provider: ^2.0.11
  printing: ^5.0.0
  flutter_pdfview: ^1.3.1
  qr: ^3.0.1
  qr_flutter: ^4.0.0
  webview_flutter: ^4.10.0
  flutter_riverpod: ^2.6.1
  intl: ^0.17.0
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts: 
    - family: Anton
      fonts: 
        - asset: fonts/Anton-Regular.ttf